/* eslint-disable @typescript-eslint/no-explicit-any */
import { describe, expect, it } from "vitest";
import { auditCommercialFunnel } from "./commercial-funnel-audit";

const project = { id: "proj", publicId: "pub", title: "Project", address: "45 Broken Head Road, Byron Bay NSW", zoning: "SP3 Tourist", zoningName: "SP3 Tourist", zoningCode: "SP3" };
const siteContext = { formattedAddress: project.address, lgaName: "Byron Shire", lgaCode: "BYRON", zone: "SP3 Tourist" };
const date = (s: string) => new Date(s);
const row = (id: string, type: string, payload: any, generatedAt: string) => ({ id, type, payload, projectId: "proj", title: id, capturedAt: date(generatedAt), createdAt: date(generatedAt) });
const qsc = (id = "qsc", overrides: any = {}, generatedAt = "2026-07-15T00:00:00Z") => row(id, "quick_site_check", {
  projectId: "proj", generatedAt, site: { address: project.address, lga: "Byron Shire", zoneCode: "SP3", zoneName: "Tourist", zoneLabel: "SP3 Tourist" },
  lepInstrument: { name: "Byron LEP", code: "BYRON", lga: "Byron", source: "ingestion" },
  permissibility: { zoneLabel: "SP3 Tourist", permittedWithoutConsent: [], permittedWithConsent: [], prohibited: [], interpretation: "cited" },
  controls: { heightOfBuilding: { label: "Height", value: "9m", present: true, source: "lep", clauseRef: "4.3", interpretation: "cited" }, floorSpaceRatio: { label: "FSR", value: "1:1", present: true, source: "lep", clauseRef: "4.4", interpretation: "cited" }, minimumLotSize: { label: "MLS", value: null, present: false, source: null, clauseRef: null, interpretation: "none" } },
  notes: [], nextSteps: [], lepEvidenceSummary: { label: "Cited", detail: "3 cited", citedControlCount: 3, totalControlCount: 3, landUseEntryCount: 1, objectiveCount: 1, sourceRef: "BYRON" }, ...overrides,
}, generatedAt);
const dpp = (id = "dpp", sourceQsc = "qsc", commercialReady = true, generatedAt = "2026-07-15T00:10:00Z", overrides: any = {}) => row(id, "detailed_planning_pack", {
  packType: "detailed_planning_pack", generatedAt, projectId: "proj", site: { address: project.address, lga: "Byron Shire", lgaCode: "BYRON", zoneCode: "SP3", zoneName: "Tourist", zoneLabel: "SP3 Tourist" }, proposalBrief: "shop fitout",
  sourceQuickSiteCheck: { artefactId: sourceQsc, title: "QSC", generatedAt: null, lepEvidenceSummary: null }, carriedLepEvidenceSummary: null,
  dcpEvidence: commercialReady ? [{ topicId: "setbacks", topicLabel: "Setbacks", status: "Cited", reason: "ok", citations: [{ ref: "D4", title: "D4 Business & Commercial Development", headingPath: ["Part D"], excerpt: "nil / 0m setback applies", score: 1 }] }] : [],
  topicMatrix: commercialReady ? [{ topicId: "setbacks", topicLabel: "Setbacks", status: "Cited", summary: "ok", sourceRefs: ["D4"] }] : [], unresolvedTopics: commercialReady ? [] : ["Setbacks: unavailable"], consultantReviewQuestions: [], nextAction: "next", commercialReady, ...overrides,
}, generatedAt);
const see = (id = "see", dppId = "dpp", qscId = "qsc", generatedAt = "2026-07-15T00:20:00Z", overrides: any = {}) => row(id, "pre_see_planning_memo", {
  memoType: "pre_see_planning_memo", generatedAt, projectId: "proj", siteDescription: { address: project.address, lga: "Byron Shire", zoneCode: "SP3", zoneName: "Tourist", zoneLabel: "SP3 Tourist" }, proposedWorksSummary: "shop fitout",
  applicableControls: { lepInstrument: null, permissibility: null, quickSiteControls: { height: { clauseRef: "4.3" } }, dcpClauses: [{ ref: "D4", title: "D4 Business & Commercial Development", headingPath: ["Part D"], bodyText: "nil / 0m setback applies", score: 1 }], sourceExcerpts: [], statutoryContext: null, groundingInstructions: [] },
  consistencyAssessment: [{ topic: "Setbacks", assessment: "ok", citations: [{ ref: "D4", type: "DCP" }] }], limitations: [], sourceDetailedPlanningPack: { artefactId: dppId, title: "DPP", generatedAt: null, commercialReady: true, sourceQuickSiteCheckArtefactId: qscId }, ...overrides,
}, generatedAt);
const prismaFor = (artefacts: any[], proj: any = project) => ({
  project: { findFirst: async ({ where }: any) => where.OR.some((x: any) => x.id === "proj" || x.publicId === "pub") ? proj : null, findUnique: async () => ({ ...proj, siteContext }) },
  artefact: { findMany: async () => artefacts, create: async () => { throw new Error("mutation called"); }, update: async () => { throw new Error("mutation called"); }, upsert: async () => { throw new Error("mutation called"); }, delete: async () => { throw new Error("mutation called"); } },
} as any);
const audit = (artefacts: any[]) => auditCommercialFunnel("pub", { prisma: prismaFor(artefacts) });

describe("auditCommercialFunnel", () => {
  it("returns unknown project honestly", async () => expect(await auditCommercialFunnel("missing", { prisma: prismaFor([], null) })).toMatchObject({ project: null, error: "project_not_found" }));
  it("is read-only and reports Byron quality chain with exact IDs", async () => expect(await audit([qsc(), dpp(), see()])).toMatchObject({ quickSiteCheck: { artefactId: "qsc", state: "ready" }, detailedPlanningPack: { artefactId: "dpp", sourceQuickSiteCheckArtefactId: "qsc", state: "ready" }, see: { artefactId: "see", sourceDetailedPlanningPackArtefactId: "dpp", sourceQuickSiteCheckArtefactId: "qsc", state: "ready" }, referralEligibility: "quality_chain_referral" }));
  it("accepts a legitimate publicId QSC report projectId in the exact chain", async () => expect(await audit([qsc("qsc-public", { projectId: "pub" }), dpp("dpp-public", "qsc-public"), see("see-public", "dpp-public", "qsc-public")])).toMatchObject({ quickSiteCheck: { artefactId: "qsc-public", state: "ready" }, detailedPlanningPack: { artefactId: "dpp-public", sourceQuickSiteCheckArtefactId: "qsc-public", state: "ready" }, referralEligibility: "quality_chain_referral" }));
  it("rejects a forged unrelated QSC report projectId", async () => expect(await audit([qsc("forged-qsc", { projectId: "evil" }), dpp("dpp-forged-qsc", "forged-qsc")])).toMatchObject({ detailedPlanningPack: { state: "stale_mismatched_malformed" }, referralEligibility: "none" }));
  it("accepts Kempsey E2 D4 nil/0m evidence without conflicting-scope upgrade", async () => { const kProject = { ...project, address: "52 Belgrave St, Kempsey NSW 2440", zoning: "E2 Commercial Centre", zoningCode: "E2" }; const kSite = { formattedAddress: kProject.address, lgaName: "Kempsey Shire", lgaCode: "KEMPSEY", zone: "E2 Commercial Centre" }; const kScope = { address: kProject.address, lga: "Kempsey Shire", lgaCode: "KEMPSEY", zoneCode: "E2", zoneName: "Commercial Centre", zoneLabel: "E2 Commercial Centre" }; const rows = [qsc("kq", { site: kScope }), dpp("kd", "kq", true, "2026-07-15T00:10:00Z", { site: kScope }), see("ks", "kd", "kq", "2026-07-15T00:20:00Z", { siteDescription: { address: kProject.address, lga: "Kempsey Shire", zoneCode: "E2", zoneName: "Commercial Centre", zoneLabel: "E2 Commercial Centre" } })]; const p = prismaFor(rows, kProject); p.project.findUnique = async () => ({ ...kProject, siteContext: kSite }); const result = await auditCommercialFunnel("pub", { prisma: p }); expect(result).toMatchObject({ referralEligibility: "quality_chain_referral", detailedPlanningPack: { citedTopicCount: 1 } }); });
  it("uses newest active unresolved DPP over older ready and omits SEE readiness", async () => expect(await audit([qsc(), dpp("ready", "qsc", true, "2026-07-15T00:10:00Z"), see("old-see", "ready", "qsc"), dpp("unresolved", "qsc", false, "2026-07-15T00:30:00Z")])).toMatchObject({ detailedPlanningPack: { artefactId: "unresolved", state: "needs_expert_review" }, see: { state: "stale_mismatched_legacy" }, referralEligibility: "unresolved_pack_referral" }));
  it("anchors QSC section to selected DPP source despite newer unrelated cited QSC", async () => expect(await audit([qsc("source", {}, "2026-07-15T00:00:00Z"), qsc("newer", {}, "2026-07-15T00:50:00Z"), dpp("dpp", "source"), see("see", "dpp", "source")])).toMatchObject({ quickSiteCheck: { artefactId: "source" }, detailedPlanningPack: { sourceQuickSiteCheckArtefactId: "source" } }));
  it("skips newer stale DPP for older valid current chain", async () => expect(await audit([qsc(), dpp("valid", "qsc", true, "2026-07-15T00:10:00Z"), see("see", "valid", "qsc"), dpp("stale", "qsc", true, "2026-07-15T00:40:00Z", { site: { address: "1 Fake St", lga: "Sydney", lgaCode: "SYDNEY", zoneCode: "R1", zoneName: "Residential", zoneLabel: "R1 Residential" } })])).toMatchObject({ detailedPlanningPack: { artefactId: "valid", state: "ready" }, referralEligibility: "quality_chain_referral" }));
  it("fails stale-only, broken QSC ID, forged payload project, malformed DPP", async () => { for (const rows of [[qsc(), dpp("stale", "qsc", true, "2026-07-15T00:00:00Z", { site: { address: "1 Fake" } })], [qsc(), dpp("broken", "missing")], [qsc(), dpp("forged", "qsc", true, "2026-07-15T00:00:00Z", { projectId: "evil" })], [qsc(), row("bad", "detailed_planning_pack", { nope: true }, "2026-07-15T00:00:00Z")]]) expect(await audit(rows as any)).toMatchObject({ referralEligibility: "none", detailedPlanningPack: { state: "stale_mismatched_malformed" } }); });
  it("rejects mismatched SEE DPP/QSC IDs and malformed/legacy SEE", async () => { for (const badSee of [see("s1", "other", "qsc"), see("s2", "dpp", "other"), row("legacy", "pre_see_planning_memo", { memoType: "pre_see_planning_memo" }, "2026-07-15T00:50:00Z")]) expect(await audit([qsc(), dpp(), badSee])).toMatchObject({ detailedPlanningPack: { state: "ready" }, see: { state: "stale_mismatched_legacy" }, referralEligibility: "none" }); });
  it("orders generatedAt before capturedAt/createdAt and ignores input order", async () => { const a = dpp("a", "qsc", true, "2026-07-15T00:10:00Z"); const b = dpp("b", "qsc", false, "2026-07-15T00:30:00Z"); expect(await audit([b, qsc(), a])).toMatchObject({ detailedPlanningPack: { artefactId: "b" }, referralEligibility: "unresolved_pack_referral" }); expect(await audit([a, qsc(), b])).toMatchObject({ detailedPlanningPack: { artefactId: "b" } }); });
});
