default_platform(:ios)

platform :ios do
  desc "Build and deploy to TestFlight"
  lane :beta do
    setup_ci if ENV['CI']

    match(
      type: "appstore",
      app_identifier: "com.drme.journal",
      readonly: is_ci,
    )

    build_app(
      workspace: "Runner.xcworkspace",
      scheme: "Runner",
      export_options: "ExportOptions.plist",
    )

    upload_to_testflight(
      skip_waiting_for_build_processing: true,
    )
  end

  desc "Build for local testing"
  lane :build do
    build_app(
      workspace: "Runner.xcworkspace",
      scheme: "Runner",
      configuration: "Release",
    )
  end
end
